# C4.5 Algo  https://en.wikipedia.org/wiki/C4.5_algorithm
# C4.5 is an algorithm used to generate a decision tree developed by Ross Quinlan.[1] C4.5 is an extension of Quinlan's earlier ID3 algorithm. The decision trees generated by C4.5 can be used for classification, 
# and for this reason, C4.5 is often referred to as a statistical classifier.
# C4.5 builds decision trees from a set of training data in the same way as ID3, using the concept of information entropy.
# At each node of the tree, C4.5 chooses the attribute of the data that most effectively splits its set of samples into subsets enriched in one class or the other. The splitting criterion is the normalized information gain (difference in entropy). The attribute with the highest normalized information gain is chosen to make the decision. 
# The C4.5 algorithm then recurs on the smaller sublists.
# C5.0 offers a number of improvements on C4.5. 

#https://www.r-bloggers.com/r-talks-to-weka-about-data-mining/
summary(iris)
library(RWeka)
iris_j48 <- J48(Species ~ ., data = iris)
iris_j48
summary(iris_j48)
plot(iris_j48)

# Evaluation
eval_j48 <- evaluate_Weka_classifier(iris_j48, numFolds = 10, complexity = FALSE, 
    seed = 1, class = TRUE)
eval_j48

# More Functions
WOW("J48")

j48_control <- J48(Species ~ ., data = iris, control = Weka_control(M = 10))
j48_control

# Cost Sensitive Cls
csc <- CostSensitiveClassifier(Species ~ ., data = iris, control = Weka_control(`cost-matrix` = matrix(c(0, 
    10, 0, 0, 0, 0, 0, 10, 0), ncol = 3), W = "weka.classifiers.trees.J48", 
M = TRUE))
csc

matrix(c(0, 1, 0, 0, 0, 0, 0, 1, 0), ncol = 3)
eval_csc <- evaluate_Weka_classifier(csc, numFolds = 10, complexity = FALSE, 
    seed = 1, class = TRUE)
eval_csc
